applications:
- api_domain: api.entitle.io
  application_name: Entitle API
  authentication_key: Authorization
  authentication_mode: header-bearer
  authentication_value: ${{ jit_secrets.api_scan_authentication_value }}
  exclude_paths: []
  target_url: .jit/api.json
  type: api
foo: bar
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
license-compliance:
  deny_list:
    - GPL
